spring:
    datasource:
        url: jdbc:mysql://localhost:3306/TAFEI_MALL?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: TAFEI_MALL
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
        id-type: auto